Vagrant.configure("2") do |config|

  # ------------------ BLOCK WEB SERVERS ------------------
  servers = {
    "dev" => { :box => "ubuntu/jammy64", :host_os => "ub", :ip => "192.168.20.88" },
    # "qa" => { :box => "eurolinux-vagrant/oracle-linux-8", :host_os => "or", :ip => "192.168.20.99" }
  }
  servers.each do |server, info|
    config.vm.define "#{server}" do |node|
      node.vm.hostname = "#{server}"
      node.vm.box = "#{info[:box]}"
      node.vm.network "public_network", ip: "#{info[:ip]}"
      node.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.name = "#{server}"
        vb.memory = "1024"
        vb.cpus = 1
      end
      # server configure
      # node.vm.provision "configure #{server}", type: "shell" do |s|
      #   s.path = "local_config/web.sh"
      #   s.args = ["#{info[:host_os]}", "#{info[:srv]}"]
      # end # end server configure
      # set nameserver and domain config
      # node.vm.provision "set nameserver and domain config", type: "shell", path: "local_config/resolve.sh"
      # ssh access configuration
      node.vm.provision "configure ssh access to #{server}", type: "shell" do |s|
        s.path = "ssh_access.sh"
        s.args = "#{info[:host_os]}"
      end # end ssh configure
    end # end config
  end # end servers
end