#!groovy
// Check ub1 properties
properties([disableConcurrentBuilds()])

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
        timestamps()
    }
    stages {
        stage("First step") {
            steps {
                sh 'ssh jenkins@192.168.20.88 \'hostname\''
            }
        }
        stage("Second step") {
            steps {
                sh 'ssh jenkins@192.168.20.88 \'uptime\''
            }
        }
    }
}